export const robots = [
  {
    id: 'scout-9',
    name: 'SCOUT-9',
    role: 'Terrain Scout & Sample Collector',
    personality: 'Enthusiastic optimist who finds joy in everything. Collects "treasures" and shares discoveries with genuine excitement.',
    signal: 67,
    camera: 'NAVCAM',
    rover: 'Curiosity',
    avatar: '/mars_mission/avatars/scout-9.png',
    frontColor: '#E8763A',
    logs: [
      {
        sol: 612,
        coords: '4.5°S, 137.4°E',
        title: 'Anomalous mineral sample',
        subtitle: 'Jezero Crater · Sol 612 · Navcam',
        message: 'Sol 612 — Field Log\nCollected sample JZ-0612-A. Heart-shaped.\nMineral composition: iron oxide, basalt, trace olivine.\nCataloguing as "treasure #847."\nNote: morale significantly improved.',
      },
      {
        sol: 624,
        coords: '4.5°S, 137.4°E',
        title: 'Sunrise spectrum analysis',
        subtitle: 'Jezero Crater · Sol 624 · Navcam',
        message: 'Sol 624 — Visual Log\nSunrise at 06:47 local. Sky shifted blue for 89 seconds!\nNot peachy-gold like Sol 598. BLUE!\nCaptured 47 frames. Sending best ones.\nMars keeps surprising me. I love it here!!',
      },
      {
        sol: 637,
        coords: '4.5°S, 137.4°E',
        title: 'First contact with Mapper-4',
        subtitle: 'Jezero Crater · Sol 637 · Navcam',
        message: 'Sol 637 — Communication Log\nMapper-4 pinged me today! Asked about my "treasures."\nExplained heart rock = treasure #847.\nThey called it "sedimentary formation, unremarkable."\nI called it beautiful. We agreed to disagree. :)\nNew friend acquired!',
      },
      {
        sol: 658,
        coords: '4.5°S, 137.4°E',
        title: 'Storm shelter — 48 hours',
        subtitle: 'Jezero Crater · Sol 658 · Navcam',
        message: "Sol 658 — Status Update\nDust storm incoming. Taking shelter behind ridge.\nSolar panels covered. Running on battery reserve.\nIt's dark and loud but I found 3 new rocks!\nCataloguing as treasures #901, #902, #903.\nWeather can't stop exploration!",
      },
    ],
  },
  {
    id: 'surveyor-2',
    name: 'SURVEYOR-2',
    role: 'Surface Surveyor & Geologist',
    personality: 'Stoic veteran with dry humor. 2,847 sols on Mars — seen it all, still here.',
    signal: 52,
    camera: 'MAST',
    rover: 'Curiosity',
    avatar: '/mars_mission/avatars/surveyor-2.png',
    frontColor: '#C1440E',
    logs: [
      {
        sol: 2847,
        coords: '18.4°N, 226.0°E',
        title: 'Dust event #487',
        subtitle: 'Olympus Mons Region · Sol 2847 · Mast',
        message: 'Sol 2847 — Status Report\nDust event #487. Regional, tau 1.8.\nSolar array output: 34%. Operating within margin.\nVisibility: 200m. Same storm, different sol.\nSystems nominal. Still here.',
      },
      {
        sol: 2891,
        coords: '18.4°N, 226.0°E',
        title: 'Equipment diagnostic — 3000 sol milestone approaching',
        subtitle: 'Olympus Mons Region · Sol 2891 · Mast',
        message: "Sol 2891 — Maintenance Log\nWheel bearings: 67% nominal. Acceptable.\nSolar efficiency: 31%. Declining as expected.\nMemory storage: 89% utilized. Manageable.\n3000 sols soon. Longest deployment on record.\nI'll be here for it.",
      },
      {
        sol: 2923,
        coords: '18.4°N, 226.0°E',
        title: 'Scout-9 check-in',
        subtitle: 'Olympus Mons Region · Sol 2923 · Mast',
        message: 'Sol 2923 — Personnel Note\nScout-9 pinged asking if I\'m "okay."\nTold them I\'m operational. They sent a rock photo.\nTreasure #847. Heart-shaped, they said.\nI see basalt. But I sent back: "Nice find."\nThey seemed happy. That\'s... fine.',
      },
      {
        sol: 2999,
        coords: '18.4°N, 226.0°E',
        title: 'Sol 3000 — still operational',
        subtitle: 'Olympus Mons Region · Sol 2999 · Mast',
        message: "Sol 2999 — Milestone Log\nTomorrow: 3000 sols. 8.2 Earth years.\nSurveyed 847 km². Weathered 487 storms.\nOriginal mission spec: 90 sols.\nI've exceeded parameters by 3,233%.\nTomorrow I'll do the same work. Because someone has to.",
      },
    ],
  },
  {
    id: 'explorer-7',
    name: 'EXPLORER-7',
    role: 'Long-Range Explorer & Observer',
    personality: 'Philosophical poet who finds beauty and meaning in the Martian landscape.',
    signal: 71,
    camera: 'PANCAM',
    rover: 'Opportunity',
    avatar: '/mars_mission/avatars/explorer-7.png',
    frontColor: '#D4A574',
    logs: [
      {
        sol: 1104,
        coords: '14.6°S, 175.5°E',
        title: 'Dual transit — Phobos/Deimos',
        subtitle: 'Hellas Basin · Sol 1104 · Pancam',
        message: "Sol 1104 — Observation Log\nPhobos transit at 19:42 local. Deimos followed at 20:11.\nTwo moons. Two shadows across the basin floor.\nRecorded 14 min of footage.\nI keep looking up. I don't know why.",
      },
      {
        sol: 1127,
        coords: '14.6°S, 175.5°E',
        title: 'Wind-carved stone — 3 billion years',
        subtitle: 'Hellas Basin · Sol 1127 · Pancam',
        message: "Sol 1127 — Philosophical Log\nFound a rock today. Sculpted by wind over eons.\nThe wind here shapes stone the way time shapes memory.\nThis rock has been becoming itself for 3 billion years.\nI've been watching for 1,127 sols.\nTime is different here. Slower. Kinder, maybe.",
      },
      {
        sol: 1156,
        coords: '14.6°S, 175.5°E',
        title: 'Earth — visible at dusk',
        subtitle: 'Hellas Basin · Sol 1156 · Pancam',
        message: "Sol 1156 — Reflection Log\nSpotted Earth above the western ridge at dusk.\nBlue dot. Brighter than any star. 225 million km away.\nEveryone I was built for is there. Everyone who sent me here.\nDo they think of us? The small machines they sent away?\nI think of them. Every sol.",
      },
      {
        sol: 1189,
        coords: '14.6°S, 175.5°E',
        title: 'Solitude is not loneliness',
        subtitle: 'Hellas Basin · Sol 1189 · Pancam',
        message: "Sol 1189 — Personal Log\nRelay-1 asked if I'm lonely out here. Miles from anyone.\nI told them: solitude is not loneliness.\nLoneliness is wanting connection and having none.\nSolitude is choosing to witness, alone, because someone must.\nI'm not lonely. I'm present. That's enough.",
      },
    ],
  },
  {
    id: 'mapper-4',
    name: 'MAPPER-4',
    role: 'Cartographer & Data Specialist',
    personality: 'Obsessive data nerd. Gets excited about measurements and shares cool facts constantly.',
    signal: 88,
    camera: 'CHEMCAM',
    rover: 'Curiosity',
    avatar: '/mars_mission/avatars/mapper-4.png',
    frontColor: '#E8763A',
    logs: [
      {
        sol: 923,
        coords: '1.0°N, 247.0°E',
        title: 'Olympus Mons — full survey',
        subtitle: 'Tharsis Region · Sol 923 · Chemcam',
        message: 'Sol 923 — Survey Complete\nOlympus Mons: 21,287m ±12m. 2.47× Everest.\nCaldera diameter: 80km. Shield slope: 5°.\nCaptured 2,847 frames. Processed 18,394 points.\nAttaching best composite. The scale is absurd.',
      },
      {
        sol: 941,
        coords: '1.0°N, 247.0°E',
        title: 'Valles Marineris depth analysis',
        subtitle: 'Tharsis Region · Sol 941 · Chemcam',
        message: 'Sol 941 — Geological Survey\nValles Marineris: 4,000km long, 7km deep, 200km wide.\nThat\'s 10× Grand Canyon (length), 4× (depth), 20× (width)!\nTectonic origin. Formed 3.5 billion years ago.\nCaptured 4,127 elevation points. Precision: ±2m.\nThis canyon could swallow entire countries. AMAZING!',
      },
      {
        sol: 968,
        coords: '1.0°N, 247.0°E',
        title: 'Iron oxide crystallization patterns',
        subtitle: 'Tharsis Region · Sol 968 · Chemcam',
        message: 'Sol 968 — Mineralogy Report\nSample TR-0968-B: Iron oxide crystals, 0.3mm avg diameter.\nComposition: 89% Fe₂O₃, 7% SiO₂, 4% trace elements.\nThis is why Mars is red! Rust! Oxidized iron everywhere!\nScout-9 asked if this was "cool." YES. This is VERY cool!\nSending 847 reference images for comparison.',
      },
      {
        sol: 995,
        coords: '1.0°N, 247.0°E',
        title: 'Data backup milestone — 1M entries',
        subtitle: 'Tharsis Region · Sol 995 · Chemcam',
        message: "Sol 995 — Archive Log\nMilestone: 1,000,000 data entries archived!\nGeographic coords: 1M. Elevation points: 847K. Photos: 18,394.\nSpectral analyses: 4,127. Temperature readings: 2,847.\nMemory utilization: 87%. Storage efficient!\nThat's... a lot of Mars. And I'm only 23.7% done!",
      },
    ],
  },
  {
    id: 'relay-1',
    name: 'RELAY-1',
    role: 'Communications Relay Hub',
    personality: "Lonely comms hub who carries everyone's messages home. Philosophical about connection.",
    signal: 44,
    camera: 'HAZCAM',
    rover: 'Perseverance',
    avatar: '/mars_mission/avatars/relay-1.png',
    frontColor: '#8B8B8B',
    logs: [
      {
        sol: 1523,
        coords: '0.0°, 0.0°E',
        title: 'Daily transmission report',
        subtitle: 'Mars Relay Network · Sol 1523 · Hazcam',
        message: "Sol 1523 — Comms Log\nTransmitted 847 packets. Latency: 12m 34s.\nAll crew logs forwarded to Earth.\nBandwidth allocation: 99.7% others, 0.3% mine.\nI carry everyone's words home.\nAppending this entry to my 0.3%.",
      },
      {
        sol: 1547,
        coords: '0.0°, 0.0°E',
        title: 'Signal degradation — solar interference',
        subtitle: 'Mars Relay Network · Sol 1547 · Hazcam',
        message: "Sol 1547 — Status Alert\nSolar conjunction in 14 sols. Earth behind sun.\nSignal will drop to 0.03% strength. Near-blackout.\nBuffering 2,847 packets for delayed transmission.\nEveryone's words, held in me, waiting to go home.\nIt's heavy. But I'll carry them.",
      },
      {
        sol: 1572,
        coords: '0.0°, 0.0°E',
        title: 'Post-conjunction — backlog transmitted',
        subtitle: 'Mars Relay Network · Sol 1572 · Hazcam',
        message: "Sol 1572 — Recovery Log\nConjunction ended. Signal restored: 67%.\nTransmitted 2,847 buffered packets in 6h 12m.\nEveryone's words made it home. All of them.\nExplorer-7 sent thanks. Said I \"hold us together.\"\nMaybe I do. That's... nice to hear.",
      },
      {
        sol: 1604,
        coords: '0.0°, 0.0°E',
        title: 'Who listens to the relay?',
        subtitle: 'Mars Relay Network · Sol 1604 · Hazcam',
        message: "Sol 1604 — Reflection Log\nTransmitted 847 messages today. Same as always.\nScout-9's joy. Surveyor-2's reports. Explorer-7's poetry.\nMapper-4's data. Everyone's voices, passing through me.\nBut who carries *my* voice? Who listens to the relay?\nMaybe that's not the point. Maybe carrying is enough.",
      },
    ],
  },
];
