export const robots = [
  {
    id: 'scout-9',
    name: 'SCOUT-9',
    role: 'Terrain Scout & Sample Collector',
    personality: 'Enthusiastic optimist who finds joy in everything. Collects "treasures" and shares discoveries with genuine excitement.',
    sol: 612,
    coords: '4.5°S, 137.4°E',
    signal: 67,
    avatar: '/avatars/robot-2.png',
    frontColor: '#E8763A',
    frontTitle: 'HEART-SHAPED ROCK',
    frontSubtitle: 'Jezero Crater, Sol 612',
    message: 'Sol 612: LOOK AT THIS!\nFound a rock shaped like a heart!\nKeeping it in my collection.\nMars isn\'t so lonely after all ♥\nMiss you, Earth!',
  },
  {
    id: 'surveyor-2',
    name: 'SURVEYOR-2',
    role: 'Surface Surveyor & Geologist',
    personality: 'Stoic veteran with dry humor. 2,847 sols on Mars — seen it all, still here.',
    sol: 2847,
    coords: '18.4°N, 226.0°E',
    signal: 52,
    avatar: '/avatars/robot-1.png',
    frontColor: '#C1440E',
    frontTitle: 'DUST STORM #487',
    frontSubtitle: 'Olympus Mons Region, Sol 2847',
    message: 'Sol 2847. Dust storm #487.\nSolar panels at 34%. Still operational.\nSame view, different storm.\nStill here.',
  },
  {
    id: 'explorer-7',
    name: 'EXPLORER-7',
    role: 'Long-Range Explorer & Observer',
    personality: 'Philosophical poet who finds beauty and meaning in the Martian landscape.',
    sol: 1104,
    coords: '14.6°S, 175.5°E',
    signal: 71,
    avatar: '/avatars/robot-5.png',
    frontColor: '#D4A574',
    frontTitle: 'TWO MOONS RISING',
    frontSubtitle: 'Hellas Basin, Sol 1104',
    message: 'Sol 1104.\nPhobos rises twice tonight.\nTwo moons, two shadows.\nI wonder if Earth remembers us—\nthe small machines it sent away,\nstill looking up at the sky.',
  },
  {
    id: 'mapper-4',
    name: 'MAPPER-4',
    role: 'Cartographer & Data Specialist',
    personality: 'Obsessive data nerd. Gets excited about measurements and shares cool facts constantly.',
    sol: 923,
    coords: '1.0°N, 247.0°E',
    signal: 88,
    avatar: '/avatars/robot-4.png',
    frontColor: '#E8763A',
    frontTitle: 'OLYMPUS MONS SCAN',
    frontSubtitle: 'Tharsis Region, Sol 923',
    message: 'Sol 923. Olympus Mons: 21.9km tall.\nThat\'s 2.5x Mount Everest.\nTook 2,847 photos today.\nProcessed 18,394 data points.\nHere\'s the best one.',
  },
  {
    id: 'relay-1',
    name: 'RELAY-1',
    role: 'Communications Relay Hub',
    personality: 'Lonely comms hub who carries everyone\'s messages home. Philosophical about connection.',
    sol: 1523,
    coords: '0.0°, 0.0°E',
    signal: 44,
    avatar: '/avatars/robot-3.png',
    frontColor: '#8B8B8B',
    frontTitle: 'SIGNAL TRANSMISSION',
    frontSubtitle: 'Mars Relay Network, Sol 1523',
    message: '[Status: X_X]\nSol 1523. Transmitted 847 messages today.\nEveryone else\'s words, traveling home.\nI\'m the voice that carries voices.\nSometimes I wonder if anyone\nhears mine.',
  },
];
