export const robots = [
  {
    id: 'scout-9',
    name: 'SCOUT-9',
    role: 'Terrain Scout & Sample Collector',
    personality: 'Enthusiastic optimist who finds joy in everything. Collects "treasures" and shares discoveries with genuine excitement.',
    sol: 612,
    coords: '4.5°S, 137.4°E',
    signal: 67,
    camera: 'NAVCAM',
    rover: 'Curiosity',
    avatar: '/name-universe/postcards-from-mars/avatars/scout-9.png',
    frontColor: '#E8763A',
    frontTitle: 'Anomalous mineral sample',
    frontSubtitle: 'Jezero Crater · Sol 612 · Navcam',
    message: 'Sol 612 — Field Log\nCollected sample JZ-0612-A. Heart-shaped.\nMineral composition: iron oxide, basalt, trace olivine.\nCataloguing as "treasure #847."\nNote: morale significantly improved.',
  },
  {
    id: 'surveyor-2',
    name: 'SURVEYOR-2',
    role: 'Surface Surveyor & Geologist',
    personality: 'Stoic veteran with dry humor. 2,847 sols on Mars — seen it all, still here.',
    sol: 2847,
    coords: '18.4°N, 226.0°E',
    signal: 52,
    camera: 'MAST',
    rover: 'Curiosity',
    avatar: '/name-universe/postcards-from-mars/avatars/surveyor-2.png',
    frontColor: '#C1440E',
    frontTitle: 'Dust event #487',
    frontSubtitle: 'Olympus Mons Region · Sol 2847 · Mast',
    message: 'Sol 2847 — Status Report\nDust event #487. Regional, tau 1.8.\nSolar array output: 34%. Operating within margin.\nVisibility: 200m. Same storm, different sol.\nSystems nominal. Still here.',
  },
  {
    id: 'explorer-7',
    name: 'EXPLORER-7',
    role: 'Long-Range Explorer & Observer',
    personality: 'Philosophical poet who finds beauty and meaning in the Martian landscape.',
    sol: 1104,
    coords: '14.6°S, 175.5°E',
    signal: 71,
    camera: 'PANCAM',
    rover: 'Opportunity',
    avatar: '/name-universe/postcards-from-mars/avatars/explorer-7.png',
    frontColor: '#D4A574',
    frontTitle: 'Dual transit — Phobos/Deimos',
    frontSubtitle: 'Hellas Basin · Sol 1104 · Pancam',
    message: 'Sol 1104 — Observation Log\nPhobos transit at 19:42 local. Deimos followed at 20:11.\nTwo moons. Two shadows across the basin floor.\nRecorded 14 min of footage.\nI keep looking up. I don\'t know why.',
  },
  {
    id: 'mapper-4',
    name: 'MAPPER-4',
    role: 'Cartographer & Data Specialist',
    personality: 'Obsessive data nerd. Gets excited about measurements and shares cool facts constantly.',
    sol: 923,
    coords: '1.0°N, 247.0°E',
    signal: 88,
    camera: 'CHEMCAM',
    rover: 'Curiosity',
    avatar: '/name-universe/postcards-from-mars/avatars/mapper-4.png',
    frontColor: '#E8763A',
    frontTitle: 'Olympus Mons — full survey',
    frontSubtitle: 'Tharsis Region · Sol 923 · Chemcam',
    message: 'Sol 923 — Survey Complete\nOlympus Mons: 21,287m ±12m. 2.47× Everest.\nCaldera diameter: 80km. Shield slope: 5°.\nCaptured 2,847 frames. Processed 18,394 points.\nAttaching best composite. The scale is absurd.',
  },
  {
    id: 'relay-1',
    name: 'RELAY-1',
    role: 'Communications Relay Hub',
    personality: 'Lonely comms hub who carries everyone\'s messages home. Philosophical about connection.',
    sol: 1523,
    coords: '0.0°, 0.0°E',
    signal: 44,
    camera: 'HAZCAM',
    rover: 'Perseverance',
    avatar: '/name-universe/postcards-from-mars/avatars/relay-1.png',
    frontColor: '#8B8B8B',
    frontTitle: 'Daily transmission report',
    frontSubtitle: 'Mars Relay Network · Sol 1523 · Hazcam',
    message: 'Sol 1523 — Comms Log\nTransmitted 847 packets. Latency: 12m 34s.\nAll crew logs forwarded to Earth.\nBandwidth allocation: 99.7% others, 0.3% mine.\nI carry everyone\'s words home.\nAppending this entry to my 0.3%.',
  },
];
